name: Build AUR Package Pikaur Zip

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'The name of the AUR package to build'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Validate PACKAGE_NAME input
        id: validate
        run: |
          if [ -z "${{ github.event.inputs.package_name }}" ]; then
            echo "Error: PACKAGE_NAME input is required."
            exit 1
          fi
      - name: Enable Multilib and Update System
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo git gnupg zip
      - name: Create Non-Root User
        run: |
          useradd -m -s /bin/bash user
          echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R user:user /home/user
      - name: Clone and Build Pikaur from AUR (as non-root user)
        run: |
          # Clone pikaur from AUR as non-root user
          git clone https://aur.archlinux.org/pikaur.git
          chown -R user:user .
          cd pikaur
          # Build pikaur using makepkg as non-root user
          su user -c "MAKEFLAGS=\"-j$(nproc)\" makepkg -si --noconfirm --skippgpcheck"
      - name: Clone AUR Package (as non-root user)
        run: |
          # Clone the requested package from AUR as non-root user
          git clone "https://aur.archlinux.org/${{ github.event.inputs.package_name }}.git"
          cd "${{ github.event.inputs.package_name }}"
      - name: Build Package Using Pikaur (as non-root user)
        working-directory: ${{ github.event.inputs.package_name }}
        run: |
          # Build the AUR package using pikaur as non-root user
          su user -c "MAKEFLAGS=\"-j$(nproc)\" pikaur -Sw --noconfirm --mflags=--skippgpcheck --mflags=--skipchecksums" ${{ github.event.inputs.package_name }}"
          echo "Changing to the /home/user/.cache/pikaur/pkg directory"
          cd /home/user/.cache/pikaur/pkg
          echo "Listing files:"
          ls -l *.pkg.tar.zst
      - name: Zip the package files
        run: |
          cd /home/user/.cache/pikaur/pkg
          zip -r "${{ github.event.inputs.package_name }}.zip" *.pkg.tar.zst
          ls -l 
      - name: Upload Built Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package_name }}  # Use the package_name as the artifact name
          path: /home/user/.cache/pikaur/pkg/${{ github.event.inputs.package_name }}.zip
          if-no-files-found: warn
