name: Build Multiple PKGBUILDs

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build all PKGBUILDs in Arch Linux container as nobody
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            # Update the system and install required packages
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel

            # Adjust permissions for the nobody user
            chown -R nobody /workspace

            # Build each PKGBUILD as the nobody user
            find /workspace -name "PKGBUILD" -execdir runuser -u nobody -- makepkg -s --noconfirm \;

      - name: Upload all built package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-packages
          path: '**/*.pkg.tar.zst'
