name: Build Multiple PKGBUILDs

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile
        run: |
          # Enable multilib and update the system with necessary packages
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo gnupg

          # Create non-root user with sudo privileges
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          # Change ownership of the current directory to the user
          chown user -R .

          # Use all cores for makepkg
          export MAKEFLAGS="-j$(nproc)"

          # Run makepkg as non-root user for all PKGBUILDs with signature check skipped
          su user -c "find . -name 'PKGBUILD' -execdir makepkg -s --noconfirm --skippgpcheck \;"

      - name: Upload built packages individually
        run: |
          # Loop through all built packages and create a separate step for each upload
          for pkg in $(find . -name '*.pkg.tar.zst'); do
            pkg_name=$(basename "$pkg")
            folder_name=$(basename $(dirname "$pkg"))
            echo "Uploading $folder_name..."
            mkdir -p $HOME/$folder_name
            cp "$pkg" $HOME/$folder_name/
            
            # Dynamically create a step for each artifact upload
            echo "name: Upload $folder_name" >> $GITHUB_ENV
            echo "path: $HOME/$folder_name/*" >> $GITHUB_ENV
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}
          path: ${{ env.path }}
