name: Build PKGBUILDs

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'The name of the package folder to build (contains the PKGBUILD)'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate PACKAGE_NAME input
        id: validate
        run: |
          if [ -z "${{ github.event.inputs.package_name }}" ]; then
            echo "Error: PACKAGE_NAME input is required."
            exit 1
          fi
          if [ ! -f "${{ github.event.inputs.package_name }}/PKGBUILD" ]; then
            echo "Error: PKGBUILD not found in the specified package folder: ${{ github.event.inputs.package_name }}"
            exit 1
          fi

      - name: Enable Multilib and Update System
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo gnupg

      - name: Create Non-Root User
        run: |
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R .

      - name: Compile Specified Package
        working-directory: ${{ github.event.inputs.package_name }}
        run: |
          su user -c "MAKEFLAGS=\"-j$(nproc)\" makepkg -s --noconfirm --skippgpcheck"

      - name: Upload Built Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package_name }}
          path: |
            ${{ github.event.inputs.package_name }}/*.pkg.tar.zst
          if-no-files-found: warn
