name: Build Multiple PKGBUILDs (Manual Trigger)

on:
  workflow_dispatch:  # Only manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build all PKGBUILDs in Arch Linux container
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel

            # Find all PKGBUILD files and build each one
            find /workspace -name "PKGBUILD" -execdir bash -c "makepkg -s --noconfirm" \;

      - name: Upload all built package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-packages
          path: '**/*.pkg.tar.zst'
