name: Build Multiple PKGBUILDs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect package folders
        id: detect
        run: |
          # Find directories with PKGBUILD files and output them as a comma-separated list
          packages=$(find . -type f -name 'PKGBUILD' -exec dirname {} \; | sed 's|^\./||' | tr '\n' ',' | sed 's/,$//')
          echo "Detected packages: $packages"
          echo "::set-output name=packages::$packages"
          
  # Run separate jobs for each package detected
  build:
    needs: detect-packages
    runs-on: ubuntu-latest
    container: archlinux:latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.detect-packages.outputs.packages) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and compile PKGBUILD
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R . 

          # Build the PKGBUILD for the selected package in the matrix
          su user -c "cd ${{ matrix.package }} && yes | PKGDEST=/tmp/${{ matrix.package }} makepkg --noconfirm --skippgpcheck -s"

      - name: Zip the package
        run: |
          # Create a zip for the built package
          folder_name="${{ matrix.package }}"
          echo "Creating zip for $folder_name"
          zip -j "/tmp/$folder_name.zip" "/tmp/$folder_name"/*.pkg.tar.zst

      - name: Upload the zip file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-package
          path: "/tmp/${{ matrix.package }}.zip"
