name: Build Multiple PKGBUILDs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and compile PKGBUILDs
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R . 

          # Build each PKGBUILD in the subdirectories
          for dir in */; do
            if [ -f "$dir/PKGBUILD" ]; then
              su user -c "cd $dir && yes | PKGDEST=/tmp/$dir makepkg --noconfirm --skippgpcheck -s"
            fi
          done

      - name: Upload each built package separately with its folder name
        run: |
          for dir in /tmp/*/; do
            # Check if there is a package file in the directory
            if [ -f "$dir/*.pkg.tar.zst" ]; then
              # Extract folder name to use as the artifact name
              folder_name=$(basename "$dir")
              echo "Uploading package from $folder_name"
              # Upload the package as a separate artifact with the folder name as the artifact name
              echo "::set-output name=artifact_name::$folder_name"
              # Upload artifact with the name of the folder
              gh actions upload-artifact --name "$folder_name" --path "$dir/*.pkg.tar.zst"
            fi
          done
