name: Build Multiple PKGBUILDs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and compile PKGBUILDs
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R . 

          # Build each PKGBUILD in the subdirectories
          for dir in */; do
            if [ -f "$dir/PKGBUILD" ]; then
              su user -c "cd $dir && yes | PKGDEST=/tmp/$dir makepkg --noconfirm --skippgpcheck -s"
            fi
          done

      - name: Upload each built package separately
        run: |
          for dir in /tmp/*/; do
            if [ -f "$dir/*.pkg.tar.zst" ]; then
              # Extract the package file name and upload each one separately
              package_name=$(basename $dir/*.pkg.tar.zst)
              echo "Uploading $package_name"
              upload-artifact --name "$package_name" --path "$dir/*.pkg.tar.zst"
            fi
          done
