name: Build Multiple PKGBUILDs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and compile PKGBUILDs
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R . 

          # Build each PKGBUILD in the subdirectories
          for dir in */; do
            if [ -f "$dir/PKGBUILD" ]; then
              su user -c "cd $dir && yes | PKGDEST=/tmp/$dir makepkg --noconfirm --skippgpcheck -s"
            fi
          done

      - name: Create and upload each package as a zip
        run: |
          # Loop through each built package
          for dir in /tmp/*/; do
            if [ -f "$dir/*.pkg.tar.zst" ]; then
              # Extract the folder name to use as the zip name
              folder_name=$(basename "$dir")
              # Create a zip file containing the .pkg.tar.zst file
              zip -r "/tmp/$folder_name.zip" "$dir/*.pkg.tar.zst"
              echo "Uploading $folder_name.zip"
              # Upload the zip file as a separate artifact
              echo "::set-output name=artifact_name::$folder_name.zip"
              # Upload the zip file as a separate artifact
              actions/upload-artifact@v4
                with:
                  name: "$folder_name.zip"
                  path: "/tmp/$folder_name.zip"
            fi
          done
