name: Build Multiple PKGBUILDs

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build all PKGBUILDs in Arch Linux container as non-root
        uses: addnab/docker-run-action@v3
        with:
          image: archlinux:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            sudo pacman -Syu --noconfirm
            sudo pacman -S --noconfirm base-devel sudo

            sudo useradd -m builder
            echo 'builder ALL=(ALL) NOPASSWD: ALL' | sudo tee -a /etc/sudoers

            sudo chown -R builder /workspace

            # Run makepkg as non-root for all PKGBUILDs
            sudo -u builder bash -c '
              export MAKEFLAGS="-j$(nproc)"
              cd /workspace
              find . -name "PKGBUILD" -execdir makepkg -s --noconfirm \;
            '

            sudo chown -R runner:runner /workspace

      - name: Upload all built package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-packages
          path: '**/*.pkg.tar.zst'
          if-no-files-found: warn
