name: Build Multiple PKGBUILDs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: |
          # Enable multilib and update the system with necessary packages
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo gnupg

          # Create non-root user with sudo privileges
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          # Change ownership of the current directory to the user
          chown user -R .

          # Use all cores for makepkg
          export MAKEFLAGS="-j$(nproc)"

          # Run makepkg as non-root user for all PKGBUILDs with signature check skipped
          sudo -u user find . -name 'PKGBUILD' -execdir makepkg -s --noconfirm --skippgpcheck \;

          # Clean up each directory: keep only the .pkg.tar.zst file
          find . -type f -not -name "*.pkg.tar.zst" -exec rm -f {} \;
          find . -type d -empty -exec rmdir {} \;

          # Archive each directory containing .pkg.tar.zst into a tar.gz file
          for dir in $(find . -type f -name "*.pkg.tar.zst" -exec dirname {} \; | sort -u); do
            folder_name=$(basename "$dir")
            tar -czf "$folder_name.tar.gz" -C "$dir" .
          done

      - name: Upload each built package as an artifact
        run: |
          for tarball in *.tar.gz; do
            folder_name=$(basename "$tarball" .tar.gz)
            echo "Uploading $folder_name..."
            actions/upload-artifact@v3:
              name: "$folder_name"
              path: "$tarball"
