name: Build and Upload Packages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["linux-SLE15-SP6"]  # Add more packages as needed
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Arch Linux container
        uses: docker://archlinux:latest

      - name: Install dependencies for Arch Linux build
        run: |
          pacman -Sy --noconfirm base-devel sudo git
          sudo useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers

      - name: Compile PKGBUILD inside Arch container
        run: |
          su user -c "cd /workspace/${{ matrix.package }} && yes | PKGDEST=/tmp/${{ matrix.package }} makepkg --noconfirm --skippgpcheck -s"

      - name: Zip the package
        run: |
          folder_name="${{ matrix.package }}"
          zip -r "/tmp/${folder_name}.zip" "/tmp/${folder_name}"/*.pkg.tar.zst

      - name: Upload the zip file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-package
          path: "/tmp/${{ matrix.package }}.zip"
