name: Steam native runtime

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Enable Multilib and Update System
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel

      - name: Download steam-native-runtime Package and Dependencies
        run: |
          mkdir -p /home/arch/cache
          pacman -Sy --noconfirm --needed --downloadonly --cachedir=/home/arch/cache steam-native-runtime
          echo "Package and its dependencies downloaded to /home/arch/cache"
          ls -l /home/arch/cache

      - name: Extract the Downloaded Packages
        run: |
          mkdir -p /home/arch/extracted
          for pkg in /home/arch/cache/*.pkg.tar.zst; do
            echo "Extracting $pkg"
            tar -xvf "$pkg" -C /home/arch/extracted
          done
          echo "Extraction complete"
          ls -l /home/arch/extracted

      - name: Upload Extracted Files
        uses: actions/upload-artifact@v4
        with:
          name: steam-native-runtime-extracted
          path: /home/arch/extracted/
          if-no-files-found: warn
