name: Steam Download Arch

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Enable Multilib and Update System
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pman.conf
          pacman -Syu --noconfirm base-devel

      - name: Download steam Package and Dependencies
        run: |
          mkdir -p /home/arch/cache
          pacman -Sy --noconfirm --needed --downloadonly --cachedir=/home/arch/cache steam
          echo "Package and its dependencies downloaded to /home/arch/cache"
          ls -l /home/arch/cache

      - name: Extract the Downloaded Packages
        run: |
          mkdir -p /home/arch/extracted
          for pkg in /home/arch/cache/*.pkg.tar.zst; do
            echo "Extracting $pkg"
            tar -xvf "$pkg" -C /home/arch/extracted
          done
          echo "Extraction complete"
          ls -l /home/arch/extracted

      - name: Clean Up Downloaded Package Files
        run: |
          echo "Cleaning up downloaded .pkg.tar.zst files..."
          rm -f /home/arch/cache/*.pkg.tar.zst
          echo "Cleanup complete"
          ls -l /home/arch/cache

      - name: Upload Extracted Files
        uses: actions/upload-artifact@v4
        with:
          name: steam-extracted
          path: /home/arch/extracted/
          if-no-files-found: warn
